#!/usr/bin/env python

"""
Accepts an user name and returns a quick summary about the repositories and the commits made recently.
"""

import urllib2
import logging
import json

def get_repos(user):
    """accepts the user_name and gives the reporsitaries forked by him"""
    res = urllib2.urlopen("https://api.github.com/users/" + user + "/repos")
    soup = json.load(res)

    logger = logging.getLogger('github api')

    logger.info('printing','repositaries')

    for i, j in enumerate(soup):
        print soup[i]['url']


#tests
x = get_repos('pandeesh')
print(x)


